# **Module 2 讀取與選擇 Melboune Housing**

In [ ]:
import pandas as pd
melbourne_file_path = './sample_data/melb_data.csv'
melbourne_data = pd.read_csv(melbourne_file_path)

#印出所有欄位
print(melbourne_data.columns)

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [ ]:
#讀取Price欄
melbourne_price_data = melbourne_data.Price
print(melbourne_price_data.head())

0    1480000.0
1    1035000.0
2    1465000.0
3     850000.0
4    1600000.0
Name: Price, dtype: float64

In [ ]:
#任取兩欄
columns_of_interest = ['Landsize', 'BuildingArea']
two_columns_of_data = melbourne_data[columns_of_interest]
two_columns_of_data.describe()

            Landsize  BuildingArea
count   13580.000000   7130.000000
mean      558.416127    151.967650
std      3990.669241    541.014538
min         0.000000      0.000000
25%       177.000000     93.000000
50%       440.000000    126.000000
75%       651.000000    174.000000
max    433014.000000  44515.000000

# **Module 2 Read Gapminder CSV and selection**

In [ ]:
import pandas as pd
# data_url a CSV file
data_url = 'http://bit.ly/2cLzoxH'
# read data from url as pandas dataframe
gapminder = pd.read_csv(data_url)

In [ ]:
gapminder.head()

       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

In [ ]:
#設定選擇判準
is_2002 =  gapminder['year']==2002
print ("is_2002 type:", type(is_2002), "\nis_2002.dtype:", is_2002.dtype)
#DF 只讀year==2002資料
gapminder_2002 = gapminder[is_2002]
gapminder_2002.head()

is_2002 type: <class 'pandas.core.series.Series'>
is_2002.dtype: bool

        country  year         pop continent  lifeExp    gdpPercap
10  Afghanistan  2002  25268405.0      Asia   42.129   726.734055
22      Albania  2002   3508512.0    Europe   75.651  4604.211737
34      Algeria  2002  31287142.0    Africa   70.994  5288.040382
46       Angola  2002  10866106.0    Africa   41.003  2773.287312
58    Argentina  2002  38331121.0  Americas   74.340  8797.640716

In [ ]:
#Pandas Chaining
gapminder_2002 = gapminder[gapminder.year.eq(2002)]
gapminder_2002.head()

        country  year         pop continent  lifeExp    gdpPercap
10  Afghanistan  2002  25268405.0      Asia   42.129   726.734055
22      Albania  2002   3508512.0    Europe   75.651  4604.211737
34      Algeria  2002  31287142.0    Africa   70.994  5288.040382
46       Angola  2002  10866106.0    Africa   41.003  2773.287312
58    Argentina  2002  38331121.0  Americas   74.340  8797.640716

In [ ]:
#過濾Null資料
gapminder_no_NA = gapminder[gapminder.year.notnull()]

#只選擇years 在 list [1952, 2007]中的rows
years = [1952, 2007]
gapminder.year.isin(years)

0        True
1       False
2       False
3       False
4       False
        ...
1699    False
1700    False
1701    False
1702    False
1703     True
Name: year, Length: 1704, dtype: bool

In [ ]:
gapminder_years= gapminder[gapminder.year.isin(years)]
#print("gapminder_years.shape:", gapminder_years.shape)
gapminder_years

          country  year         pop continent  lifeExp    gdpPercap
0     Afghanistan  1952   8425333.0      Asia   28.801   779.445314
11    Afghanistan  2007  31889923.0      Asia   43.828   974.580338
12        Albania  1952   1282697.0    Europe   55.230  1601.056136
23        Albania  2007   3600523.0    Europe   76.423  5937.029526
24        Algeria  1952   9279525.0    Africa   43.077  2449.008185
...           ...   ...         ...       ...      ...          ...
1679   Yemen Rep.  2007  22211743.0      Asia   62.698  2280.769906
1680       Zambia  1952   2672000.0    Africa   42.038  1147.388831
1691       Zambia  2007  11746035.0    Africa   42.384  1271.211593
1692     Zimbabwe  1952   3080907.0    Africa   48.451   406.884115
1703     Zimbabwe  2007  12311143.0    Africa   43.487   469.709298

[284 rows x 6 columns]

In [ ]:
#Unique value
gapminder_years.year.unique()

array([1952, 2007])

In [ ]:
#多重條件
continents = ['Asia','Africa', 'Americas', 'Europe']
gapminder_Ocean = gapminder[~gapminder.continent.isin(continents)]
print("gapminder_ocean.shape: ", gapminder_Ocean.shape) 
gapminder[~gapminder.continent.isin(continents) & 
           gapminder.year.isin(years)]

gapminder_ocean.shape:  (24, 6)

          country  year         pop continent  lifeExp    gdpPercap
60      Australia  1952   8691212.0   Oceania   69.120  10039.59564
71      Australia  2007  20434176.0   Oceania   81.235  34435.36744
1092  New Zealand  1952   1994794.0   Oceania   69.390  10556.57566
1103  New Zealand  2007   4115771.0   Oceania   80.204  25185.00911

# **Module 2 Pandas JSON**

In [ ]:
import pandas as pd
df = pd.DataFrame([['a','b'], ['c','d']], index=['row 1', 'row 2'], columns=['col 1', 'col 2']) 
df.to_json(orient='split')

'{"columns":["col 1","col 2"],"index":["row 1","row 2"],"data":[["a","b"],["c","d"]]}'

**Orient = 'split' JSON 檔案的樣子**
<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"columns":["col 1","col 2"],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"index":["row 1","row 2"],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"data":[["a","b"],["c","d"]]<br>
}

**Orient = 'split' 讀回來**

In [ ]:
pd.read_json(_, orient='split')

      col 1 col 2
row 1     a     b
row 2     c     d

In [ ]:
df.to_json(orient='index')

'{"row 1":{"col 1":"a","col 2":"b"},"row 2":{"col 1":"c","col 2":"d"}}'

**Orient = 'index' Json file 的樣子**
<br>
{
> "row 1":{"col 1":"a","col 2":"b"},;<br>"row 2":{"col 1":"c","col 2":"d"}


}

In [ ]:
pd.read_json(_, orient='index')

      col 1 col 2
row 1     a     b
row 2     c     d

In [ ]:
df.to_json(orient='records')

'[{"col 1":"a","col 2":"b"},{"col 1":"c","col 2":"d"}]'

**Orient = 'records' JSON file 的樣子**


[
>{"col 1":"a","col 2":"b"},<br>{"col 1":"c","col 2":"d"}

]

In [ ]:
pd.read_json(_, orient='records')

  col 1 col 2
0     a     b
1     c     d

In [ ]:
df.to_json(orient='table')

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col 1","type":"string"},{"name":"col 2","type":"string"}],"primaryKey":["index"],"pandas_version":"0.20.0"},"data":[{"index":"row 1","col 1":"a","col 2":"b"},{"index":"row 2","col 1":"c","col 2":"d"}]}'

In [ ]:
#Orient = 'schema' Json File 的樣子
...
{
  "schema":
    {
      "fields":[
        {"name":"index","type":"string"},
        {"name":"col 1","type":"string"},
        {"name":"col 2","type":"string"}
      ],
      "primaryKey":["index"],
      "pandas_version":"0.20.0"},
  "data":[
        {"index":"row 1","col 1":"a","col 2":"b"},
        {"index":"row 2","col 1":"c","col 2":"d"}
  ]
}
...

In [ ]:
pd.read_json(_, orient='table')

      col 1 col 2
row 1     a     b
row 2     c     d

In [ ]:
import json
result=df.to_json(orient='table')
parsed = json.loads(result)
json.dumps(parsed, indent=4)

'{\n    "schema": {\n        "fields": [\n            {\n                "name": "index",\n                "type": "string"\n            },\n            {\n                "name": "col 1",\n                "type": "string"\n            },\n            {\n                "name": "col 2",\n                "type": "string"\n            }\n        ],\n        "primaryKey": [\n            "index"\n        ],\n        "pandas_version": "0.20.0"\n    },\n    "data": [\n        {\n            "index": "row 1",\n            "col 1": "a",\n            "col 2": "b"\n        },\n        {\n            "index": "row 2",\n            "col 1": "c",\n            "col 2": "d"\n        }\n    ]\n}'

# **Module 2 讀取數據庫資料 read_sql_table**

In [ ]:
!pip install sqlalchemy-utils

Requirement already satisfied: sqlalchemy-utils in /usr/local/lib/python3.7/dist-packages (0.37.8)
Requirement already satisfied: SQLAlchemy>=1.0 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy-utils) (1.4.22)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from sqlalchemy-utils) (1.15.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from SQLAlchemy>=1.0->sqlalchemy-utils) (4.6.4)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from SQLAlchemy>=1.0->sqlalchemy-utils) (1.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->SQLAlchemy>=1.0->sqlalchemy-utils) (3.5.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->SQLAlchemy>=1.0->sqlalchemy-utils) (3.7.4.3)

In [ ]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine ('sqlite://',echo=False)
df = pd.DataFrame({'A':pd.date_range('2013-01-01 09:00:00', periods=3), 'B':np.arange(3.0)})
df.to_sql('test_datetime', con=engine)

In [ ]:
result = pd.read_sql_table('test_datetime',con=engine)
result

   index                   A    B
0      0 2013-01-01 09:00:00  0.0
1      1 2013-01-02 09:00:00  1.0
2      2 2013-01-03 09:00:00  2.0

In [ ]:
result=result.drop('index', axis=1)
result

                    A    B
0 2013-01-01 09:00:00  0.0
1 2013-01-02 09:00:00  1.0
2 2013-01-03 09:00:00  2.0

# **Module 3 文字與時間資料處理**

In [ ]:
import numpy as np
pd.Series(['a', 'b', 'c'])
s=pd.Series(['a', 'b', 'c'], dtype="string")
s.astype("string")
s2 = pd.Series(['a_b_c', 'c_d_e', np.nan, 'f_g_h'], dtype="string")
s2.str.split('_')

0    [a, b, c]
1    [c, d, e]
2         <NA>
3    [f, g, h]
dtype: object

In [ ]:
t = pd.Series(['a', 'b', np.nan, 'd'], dtype="string")
t.str.cat(sep=',')

'a,b,d'

In [ ]:
t.str.cat(sep=',', na_rep='-')

'a,b,-,d'

# **以日為單位產生三個時間**

In [ ]:
pd.Series(range(3), index=pd.date_range('2000', freq='D', periods=3))

2000-01-01    0
2000-01-02    1
2000-01-03    2
Freq: D, dtype: int64

# **時間加法**

In [ ]:
friday = pd.Timestamp('2018-01-05')
saturday = friday + pd.Timedelta('1 day')
saturday

Timestamp('2018-01-06 00:00:00')

In [ ]:
saturday.day_name()

'Saturday'

# **產生時間系列**

In [ ]:
idx = pd.date_range('2018-01-01', periods=5, freq='H')
ts = pd.Series(range(len(idx)), index=idx)
ts

2018-01-01 00:00:00    0
2018-01-01 01:00:00    1
2018-01-01 02:00:00    2
2018-01-01 03:00:00    3
2018-01-01 04:00:00    4
Freq: H, dtype: int64

# **Time Resample**

In [ ]:
ts.resample('2H').mean()

2018-01-01 00:00:00    0.5
2018-01-01 02:00:00    2.5
2018-01-01 04:00:00    4.0
Freq: 2H, dtype: float64

# **Time Stamp**

In [ ]:
import datetime
pd.Timestamp(datetime.datetime(2012, 5, 1))

Timestamp('2012-05-01 00:00:00')

# **Time Span**

In [ ]:
pd.Period('2012-05', freq='D')

Period('2012-05-01', 'D')

# **Timestamp 指定成 DF index**

In [ ]:
dates = [pd.Timestamp('2012-05-01'), \
            pd.Timestamp('2012-05-02'), \
            pd.Timestamp('2012-05-03')]
 
ts = pd.Series(np.random.randn(3), dates)
type(ts.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [ ]:
ts.index

DatetimeIndex(['2012-05-01', '2012-05-02', '2012-05-03'], dtype='datetime64[ns]', freq=None)

In [ ]:
ts

2012-05-01   -1.071036
2012-05-02    0.160278
2012-05-03    0.622122
dtype: float64

# **Module 3 Dataframe 遺失值偵測與填補**

In [ ]:
import pandas as pd
import numpy as np
dict = {'First Score':[100, 90, np.nan, 95], 
    'Second Score': [30, 45, 56, np.nan], 
    'Third Score':[np.nan, 40, 80, 98]} 
df = pd.DataFrame(dict)
df.isnull()

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

**df.fillna(0)**

In [ ]:
df1 = df
df1.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

**df.fillna(method='pad')**

In [ ]:
df1 = df
df1.fillna(method='pad')

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

**Replace**

In [ ]:
df1 = df
df.replace(to_replace = np.nan, value = -99)

   First Score  Second Score  Third Score
0        100.0          30.0        -99.0
1         90.0          45.0         40.0
2        -99.0          56.0         80.0
3         95.0         -99.0         98.0

**Interpolate**

In [ ]:
df2 = pd.DataFrame({"A":[12, 4, 5, None, 1], 
				"B":[None, 2, 54, 3, None], 
				"C":[20, 16, None, 3, 8], 
				"D":[14, 3, None, None, 6]}) 
print (df2)
df2.interpolate(method ='linear', limit_direction ='forward')

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   9.5   4.0
3   3.0   3.0   3.0   5.0
4   1.0   3.0   8.0   6.0

# **Module 4 Outliers Detection**

In [ ]:
import numpy as np
import pandas as pd
outliers=[]

def detect_outlier(data_1):    
    threshold=3
    mean_1 = np.mean(data_1)
    std_1 =np.std(data_1)
    
    
    for y in data_1:
        z_score= (y - mean_1)/std_1 
        if np.abs(z_score) > threshold:
            outliers.append(y)
    return outliers, mean_1,std_1
my_data = [1,2,3,4,5,6,7,8,9,10,15,20,50]
outliers, mean, std = detect_outlier(my_data) 
print ("outliers:", outliers)
print ("mean:", mean)
print ("std:", std)
print ("border:[", mean - 3* std, mean + 3 * std, "]")

outliers: [50]
mean: 10.76923076923077
std: 12.410627245995798
border:[ -26.462650968756623 48.00111250721817 ]

# **Module 4 Use Z-Score to drop outliers**

In [ ]:
#calculate z-scores of `df`

from scipy import stats
df = pd.DataFrame(my_data)
z_scores = stats.zscore(df)

abs_z_scores = np.abs(z_scores)
#定義 filter entries
filtered_entries = (abs_z_scores < 3).all(axis=1)
#執行 filter
new_df = df[filtered_entries]

print(new_df)

     0
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  15
11  20

# **Module 4 Merge and Join 資料合併與重塑**

In [ ]:
d = {'lkey': ['foo', 'bar', 'baz', 'foo'], 'value': [1,2,3,4]}
A = pd.DataFrame(data=d)
A

  lkey  value
0  foo      1
1  bar      2
2  baz      3
3  foo      4

In [ ]:
d = {'rkey': ['foo', 'bar', 'qux', 'bar'], 'value': [5,6,7,8]}
B = pd.DataFrame(data=d)
B

  rkey  value
0  foo      5
1  bar      6
2  qux      7
3  bar      8

# **Outer Merge**

In [ ]:
# Outer Join
A.merge(B, left_on='lkey', right_on='rkey', how='outer')

  lkey  value_x rkey  value_y
0  foo      1.0  foo      5.0
1  foo      4.0  foo      5.0
2  bar      2.0  bar      6.0
3  bar      2.0  bar      8.0
4  baz      3.0  NaN      NaN
5  NaN      NaN  qux      7.0

# **Inner Merge**

In [ ]:
# Inner Join
A.merge(B, left_on='lkey', right_on='rkey', how='inner')

  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        4  foo        5
2  bar        2  bar        6
3  bar        2  bar        8

# **Left Merge**

In [ ]:
# Left Join
A.merge(B, left_on='lkey', right_on='rkey', how='left')

  lkey  value_x rkey  value_y
0  foo        1  foo      5.0
1  bar        2  bar      6.0
2  bar        2  bar      8.0
3  baz        3  NaN      NaN
4  foo        4  foo      5.0

# **Right Merge**

In [ ]:
# Right Join
A.merge(B, left_on='lkey', right_on='rkey', how='right')

  lkey  value_x rkey  value_y
0  foo      1.0  foo        5
1  foo      4.0  foo        5
2  bar      2.0  bar        6
3  bar      2.0  bar        8
4  NaN      NaN  qux        7

# **Join is joining *on the Index of the right DF*, and it is an Object Function**

In [ ]:
#join based on index
A.join(B, lsuffix='_l', rsuffix='_r', how='outer')

  lkey  value_l rkey  value_r
0  foo        1  foo        5
1  bar        2  bar        6
2  baz        3  qux        7
3  foo        4  bar        8

In [ ]:
import pandas as pd
pd.unique(pd.Series([2, 1, 3, 3]))
print (pd.unique(pd.Series([2, 1, 3, 3])))

[2 1 3]