# Module 7 Intro to **NDarray**

In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.shape

(2, 3)

In [ ]:
x.dtype

dtype('int32')

In [ ]:
x[1,2]

6

In [ ]:
y = x[:,1]
y

array([2, 5], dtype=int32)

In [ ]:
y[0] = 9
y

array([9, 5], dtype=int32)

In [ ]:
x

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

# **# Module 7 Numpy Basic Operations**

In [ ]:
A = np.array([[3,2],[0,1]])
B = np.array([[3,1],[2,1]])
A+B

array([[6, 3],
       [2, 2]])

In [ ]:
A*B

array([[9, 2],
       [0, 1]])

In [ ]:
A@B

array([[13,  5],
       [ 2,  1]])

In [ ]:
A.dot(B)

array([[13,  5],
       [ 2,  1]])

In [ ]:
A.transpose()

array([[3, 0],
       [2, 1]])

In [ ]:
np.linalg.inv(A)

array([[ 0.33333333, -0.66666667],
       [ 0.        ,  1.        ]])

# **Module 7 Broadcasting**

In [1]:
from numpy import array
a = array([1.0, 2.0, 3.0])
b = array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [2]:
a = array([1.0,2.0,3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [3]:
a = array([[ 0.0,  0.0,  0.0],
...            [10.0, 10.0, 10.0],
...            [20.0, 20.0, 20.0],
...            [30.0, 30.0, 30.0]])
b = array([1.0, 2.0, 3.0])
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

# **Module 8 Index 取值**

In [ ]:
import numpy as np
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [ ]:
y[1:5:2,:]

array([[ 7,  8,  9, 10, 11, 12, 13],
       [21, 22, 23, 24, 25, 26, 27]])

In [ ]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [ ]:
x = np.arange(10,1,-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

In [ ]:
x[np.array([[1,1],[2,3]])]

array([[9, 9],
       [8, 7]])

# **Module 8 Mask & Fancy Indexing**

In [ ]:
import numpy as np

rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]

In [ ]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [ ]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [ ]:
ind = np.array([[3, 7],
        [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

# **Module 8** **NDarray** **Statistics**

In [ ]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.67511302 5.8306368  5.23662839 4.5302857  4.77728861 5.0535762
 5.20500984 4.57895788 5.03124508 5.32208671]

In [ ]:
## Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

4.530285699255719
5.830636795381895
5.024082821957012
5.042410637801121
0.37984550888881646

In [ ]:
x = np.array([[4, 9, 2, 10],
        [6, 9, 7, 12]])
np.ptp(x, axis=1)

array([8, 6])

In [ ]:
np.ptp(x, axis=0)

array([2, 0, 5, 2])

In [ ]:
np.ptp(x)

10

In [ ]:
a = np.arange(4).reshape((2,2))
np.amin(a)

0

In [ ]:
np.amin(a, axis=0)

array([0, 1])

In [ ]:
np.amin(a, axis=1)

array([0, 2])

# **Module 9 Numpy NDarray Concatenate**

In [14]:
array = np.arange(9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
array2D_1 = array.reshape((3,3))
array2D_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
array2D_2 = np.arange(10,19).reshape(3,3)
array2D_2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [17]:
np.concatenate((array2D_1, array2D_2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [18]:
np.concatenate((array2D_1,array2D_2),axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [19]:
np.concatenate((array2D_1, array2D_2, array2D_1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [20]:
np.vstack((array2D_1, array2D_2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [21]:
np.hstack((array2D_1, array2D_2))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

# **Module 9 Numpy Stack**

In [5]:
import numpy as np
arrays = [np.random.randn(3, 4) for _ in range(10)]
arrays

[array([[ 0.95910504, -0.21385881,  0.0610659 ,  1.07461226],
        [-0.11194651, -0.608934  ,  1.7737779 , -0.27734405],
        [-1.28685874,  0.10706979,  2.11561057,  1.46761824]]),
 array([[ 1.90600434, -0.05662437, -1.38608764,  0.26245859],
        [-0.45515874,  0.99533052, -0.62521449, -0.98854646],
        [ 0.50660842,  0.73959892,  0.61081671,  1.20750372]]),
 array([[ 1.28833789, -0.24824492,  0.9189394 , -0.00366522],
        [-0.44679235,  0.85533211,  0.98185378,  1.28206514],
        [-0.96274602, -0.64525776,  1.27251033,  0.04007556]]),
 array([[ 0.64956062,  0.42935985, -0.23509281, -0.2211768 ],
        [-1.34505189,  0.89992273,  0.31186922, -0.82401742],
        [-0.13787568,  2.88690599, -1.41277998,  0.96510828]]),
 array([[ 0.90218278, -1.24717245,  0.51256116, -0.54310059],
        [ 0.48191204, -0.24153306,  1.01489745,  0.38570231],
        [-0.08073091, -0.57106595, -0.15231509,  1.11799969]]),
 array([[-0.92706848,  0.80448572, -0.47607745,  2.56803824],
        [-0.27548107,  0.27179306,  0.20597114,  0.59889102],
        [ 1.83745575,  0.01995847,  0.05525594,  1.44316352]]),
 array([[ 1.08406481,  1.78080692,  0.1268323 ,  0.63499098],
        [-0.06794599,  1.14765148, -0.71067601, -0.53336236],
        [ 0.83242924, -0.43187867, -0.38770422, -2.36090424]]),
 array([[-0.232437  , -0.68835258,  0.47811703,  0.36724763],
        [-1.13194726, -0.56008832,  0.46624562,  0.82699316],
        [ 0.79135256, -0.32844667,  1.26557741, -1.71714492]]),
 array([[-0.33314617,  1.4735936 ,  1.0437826 ,  0.32376325],
        [-0.20246557,  1.35048234, -0.53551342, -1.03414267],
        [-1.15645159,  1.3721319 , -0.32534543, -1.52989179]]),
 array([[-0.40729913, -0.47875835, -0.56015918, -0.08239911],
        [ 1.64537678, -0.21929213,  0.24095933, -1.16963659],
        [-1.10090258,  0.6812238 ,  1.90334636, -0.41399987]])]

In [6]:
np.stack(arrays, axis=0).shape

(10, 3, 4)

In [7]:
np.stack(arrays, axis=1).shape

(3, 10, 4)

In [8]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

In [9]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
np.stack((a, b), axis=-1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [11]:
np.stack((a,b),axis=1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [12]:
np.concatenate((a,b),axis=1)

AxisError: ignored

In [13]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 2, 3, 4])

# **Module 10 Axis in Pandas Dataframe**

In [ ]:
import pandas as pd
srs_a = pd.Series([10,30,60,80,90])
srs_b = pd.Series([22, 44, 55, 77, 101])
df = pd.DataFrame({'a': srs_a, 'b': srs_b})
df

    a    b
0  10   22
1  30   44
2  60   55
3  80   77
4  90  101

In [ ]:
dfx = df.sum(axis=0)
dfx

a    270
b    299
dtype: int64

In [ ]:
dfx.loc['b']

299

In [ ]:
dfx = df.sum(axis=1)
dfx

0     32
1     74
2    115
3    157
4    191
dtype: int64

In [ ]:
dfx.loc[2]

115

# **Module 10 Pandas Missing Data**

In [ ]:
import numpy as np
dict = {'First Score':[100, 90, np.nan, 95], 
        'Second Score': [30, 45, 56, np.nan], 
        'Third Score':[np.nan, 40, 80, 98]} 
dict

{'First Score': [100, 90, nan, 95],
 'Second Score': [30, 45, 56, nan],
 'Third Score': [nan, 40, 80, 98]}

In [ ]:
import pandas as pd
df = pd.DataFrame(dict) 
# using isnull() function   
df.isnull()

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

# **Module 10 Numpy Missing Data**

In [ ]:
import numpy as np
print (np.log(-1), np.log(0), np.log(1))
np.isnan([np.log(-1), np.log(0), np.log(1)])

nan -inf 0.0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until

array([ True, False, False])

In [ ]:
np.array([1.0, 2.0, np.NaN, 7.0])

array([ 1.,  2., nan,  7.])

In [ ]:
# sample input ndarray:
x = np.array([1.0, 2.5, np.nan, 1.3, np.inf, 7.2])
print("input array with bad values:")
print(x)

xm = np.ma.masked_invalid(x)
print("masked version:")
print(xm)

input array with bad values:
[1.  2.5 nan 1.3 inf 7.2]
masked version:
[1.0 2.5 -- 1.3 -- 7.2]

In [ ]:
x = np.ma.array([1, 2, 3], mask=[False, False, True])
y = np.ma.array([1, 0, 1])
print("x * y =", x * y)
print("x/y =", x/y)
z = np.array([1, np.nan, 2])
print("x * z = ", x * z)
print (" x/z =", x/z)

x * y = [1 0 --]
x/y = [1.0 -- --]
x * z =  [1.0 nan --]
 x/z = [1.0 -- --]

# **Module 10 Pandas Duplicated Data**

In [ ]:
# importing pandas package 
import pandas as pd 

# making data frame from csv file 
data = pd.read_csv("./sample_data/employees.csv") 

# sorting by first name 
data.sort_values("First Name", inplace = True) 

# making a bool series 
bool_series = data["First Name"].duplicated() 
bool_series

101    False
327     True
440     True
937     True
137    False
       ...
902     True
925     True
946     True
947     True
951     True
Name: First Name, Length: 1000, dtype: bool

In [ ]:
# displaying data 
print(data.head()) 

# display data 
data[bool_series]

    First Name Gender Start Date  ... Bonus %  Senior Management             Team
101      Aaron   Male  2/17/2012  ...  11.849               True        Marketing
327      Aaron   Male  1/29/1994  ...   5.097               True        Marketing
440      Aaron   Male  7/22/1990  ...  11.343               True  Client Services
937      Aaron    NaN  1/22/1986  ...  18.424              False  Client Services
137       Adam   Male  5/21/2011  ...  15.120              False     Distribution

[5 rows x 8 columns]

    First Name  Gender  Start Date  ... Bonus %  Senior Management             Team
327      Aaron    Male   1/29/1994  ...   5.097               True        Marketing
440      Aaron    Male   7/22/1990  ...  11.343               True  Client Services
937      Aaron     NaN   1/22/1986  ...  18.424              False  Client Services
141       Adam    Male  12/24/1990  ...  14.727               True          Product
302       Adam    Male    7/5/2007  ...   5.027               True  Human Resources
..         ...     ...         ...  ...     ...                ...              ...
902        NaN    Male   5/23/2001  ...   6.322                NaN     Distribution
925        NaN  Female   8/23/2000  ...  19.388                NaN            Sales
946        NaN  Female   9/15/1985  ...  16.941                NaN     Distribution
947        NaN    Male   7/30/2012  ...   5.329                NaN        Marketing
951        NaN  Female   9/14/2010  ...   9.662                NaN              NaN

[799 rows x 8 columns]

In [ ]:


# passing NOT of bool series to see unique values only 
data = data[~bool_series] 

# displaying data 
print(data.info() )
data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 201 entries, 101 to 7
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         200 non-null    object
 1   Gender             178 non-null    object
 2   Start Date         201 non-null    object
 3   Last Login Time    201 non-null    object
 4   Salary             201 non-null    int64
 5   Bonus %            201 non-null    float64
 6   Senior Management  200 non-null    object
 7   Team               197 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 14.1+ KB
None

    First Name  Gender  Start Date  ... Bonus %  Senior Management             Team
101      Aaron    Male   2/17/2012  ...  11.849               True        Marketing
137       Adam    Male   5/21/2011  ...  15.120              False     Distribution
300       Alan    Male   6/26/1988  ...   3.592               True      Engineering
372     Albert    Male    2/1/1997  ...  19.717               True      Engineering
988      Alice  Female   10/5/2004  ...  11.209              False  Human Resources
..         ...     ...         ...  ...     ...                ...              ...
433      Wanda  Female   7/20/2008  ...   7.132               True            Legal
177      Wayne    Male    4/7/2012  ...  14.085               True     Distribution
820    William    Male  11/18/1993  ...   5.182               True  Human Resources
450     Willie    Male   8/22/2009  ...  19.691              False            Legal
7          NaN  Female   7/20/2015  ...  11.598                NaN          Finance

[201 rows x 8 columns]